import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { LanguageProvider } from '@/context/LanguageContext';
import './globals.css'; // File css của bạn
import { AuthProvider } from '@/providers/auth-provider';
import { cookies } from 'next/headers';
import api from "@/lib/axios";

async function getMeFromServer() {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  if (!accessToken) return null;

  try {
    // Gọi trực tiếp sang Laravel từ Server Next.js kèm theo Cookie thu được
    const response = await api.get(`${process.env.NEXT_PUBLIC_URL}/auth/me`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    return response.data.user;
  } catch (error) {
    return null;
  }
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getMeFromServer() 
  return (
    <html>
      <body>
        {/* Bọc Provider ở đây để giữ trạng thái API mãi mãi */}
        <LanguageProvider>
          <AuthProvider initialUser={user}>{children}</AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
