import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { LanguageProvider } from '@/context/LanguageContext';
import './globals.css'; // File css của bạn
import { AuthProvider } from '@/providers/auth-provider';
import { cookies } from 'next/headers';
import api from "@/lib/axios";

import prisma from "@/lib/prisma";

async function getMeFromServer() {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  if (!accessToken) return null;

  try {
    // Dùng fetch thuần túy trên Server để tránh kích hoạt Axios Interceptor (dành riêng cho Client)
    const response = await fetch(`${process.env.NEXT_PUBLIC_URL}/auth/me`, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
    });

    if (!response.ok) {
      // Nếu 401 (hết hạn), trả về null. Client AuthProvider sẽ tự động gọi lại và kích hoạt Refresh Token!
      return null;
    }

    const data = await response.json();
    return data.user;
  } catch (error) {
    return null;
  }
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getMeFromServer();

  // Lấy dữ liệu ngôn ngữ trực tiếp từ Server (Prisma)
  const languages = await prisma.language.findMany({
    where: { is_active: true },
    orderBy: { created_at: "desc" },
  });

  return (
    <html>
      <body>
        {/* Bọc Provider ở đây để giữ trạng thái API mãi mãi */}
        <LanguageProvider initialLanguages={languages}>
          <AuthProvider initialUser={user}>{children}</AuthProvider>
        </LanguageProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
