import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { LanguageProvider } from '@/context/LanguageContext';
import './globals.css'; // File css của bạn
import { AuthProvider } from '@/providers/auth-provider';
import { cookies } from 'next/headers';
import api from "@/lib/axios";

import prisma from "@/lib/prisma";

import { createClient } from "@supabase/supabase-js";

async function getMeFromServer() {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  if (!accessToken) return null;

  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        global: { headers: { Authorization: `Bearer ${accessToken}` } },
        auth: { persistSession: false },
      }
    );

    const { data: { user }, error: userError } = await supabase.auth.getUser();

    if (userError || !user) return null;

    const dbUser = await prisma.user.findUnique({
      where: { id: user.id },
      include: { role: true },
    });

    if (!dbUser) return null;

    const { password: _, ...userWithoutPassword } = dbUser;
    return userWithoutPassword;
  } catch (error) {
    return null;
  }
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getMeFromServer();

  // Lấy dữ liệu ngôn ngữ trực tiếp từ Server (Prisma)
  const languages = await prisma.language.findMany({
    where: { is_active: true },
    orderBy: { created_at: "desc" },
  });

  return (
    <html>
      <body>
        {/* Bọc Provider ở đây để giữ trạng thái API mãi mãi */}
        <LanguageProvider initialLanguages={languages}>
          <AuthProvider initialUser={user as any}>{children}</AuthProvider>
        </LanguageProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
